### ISSUE TITLE
error in platform basic table

### ISSUE THREAD

**Issue by jyoti1507** [SAP/fundamental-ngx#10160]
#### If this is a bug, please provide steps for reproducing it.on use of basic table getting below error. its wasn't with previous version
main.ts:5 ERROR TypeError: Cannot set properties of undefined (setting 'shortRowFocus')
    at TableComponent.ngAfterViewInit (fundamental-ngx-platform-table.mjs:3355:42)
    at callHook (core.mjs:2434:22)
    at callHooks (core.mjs:2403:17)
    at executeInitAndCheckHooks (core.mjs:2354:9)
    at refreshView (core.mjs:10397:21)
    at refreshComponent (core.mjs:11385:13)
    at refreshChildComponents (core.mjs:10116:9)
    at refreshView (core.mjs:10376:13)
    at refreshComponent (core.mjs:11385:13)
    at refreshChildComponents (core.mjs:10116:9)

**Comment by droshev** [comment]
@mikerodonnell89 can you check this out?

**Comment by fkolar** [comment]
@jyoti1507, I see, there is already PR provided by Mike, but please try to describe more details next time
