### ISSUE TITLE
Radio button test failing

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-ngx#2801]
Investigate why the radio button test
`libs/core/src/lib/radio/radio-button/radio-button-reactive-form.component.spec.ts`
is failing randomly
`it('should check second radio'...`

**Comment by stefanoScalzo** [comment]
@droshev there is no test that is it ('should check second radio')

**Comment by droshev** [comment]
It is failing again:
https://travis-ci.org/github/SAP/fundamental-ngx/builds/716269340
```
Chrome Headless 62.0.3202.94 (Linux x86_64) RadioButtonComponent reactive forms should check second radio FAILED
	Error: Expected true to be falsy.
	    at <Jasmine>
	    at http://localhost:9876/_karma_webpack_/src/lib/radio/radio-button/radio-button-reactive-form.component.spec.ts:72:73
	    at step (http://localhost:9876/home/travis/build/SAP/fundamental-ngx/node_modules/tslib/tslib.es6.js:100:1)
	    at Object.next (http://localhost:9876/home/travis/build/SAP/fundamental-ngx/node_modules/tslib/tslib.es6.js:81:45)
	Error: Expected false to be truthy.
	    at <Jasmine>
	    at http://localhost:9876/_karma_webpack_/src/lib/radio/radio-button/radio-button-reactive-form.component.spec.ts:73:73
	    at step (http://localhost:9876/home/travis/build/SAP/fundamental-ngx/node_modules/tslib/tslib.es6.js:100:1)
	    at Object.next (http://localhost:9876/home/travis/build/SAP/fundamental-ngx/node_modules/tslib/tslib.es6.js:81:45)
Chrome Headless 62.0.3202.94 (Linux x86_64): Executed 16 of 291 (1 FAILED) (0 secs / 4.349 secs)
Chrome Headless 62.0.3202.94 (Linux x86_64): Executed 14 of 303 SUCCESS (0 secs / 3.37 secs)
Chrome Headless 62.0.3202.94 (Linux x86_64): Executed 0 of 260 SUCCESS (0 secs / 0 secs)
Chrome Headless 62.0.3202.94 (Linux x86_64) RadioButtonComponent reactive forms should check second radio FAILED
	Error: Expected true to be falsy.
	    at <Jasmine>
	    at http://localhost:9876/_karma_webpack_/src/lib/radio/radio-button/radio-button-reactive-form.component.spec.ts:72:73
	    at step (http://localhost:9876/home/travis/build/SAP/fundamental-ngx/node_modules/tslib/tslib.es6.js:100:1)
	    at Object.next (http://localhost:9876/home/travis/build/SAP/fundamental-ngx/node_modules/tslib/tslib.es6.js:81:45)
	Error: Expected false to be truthy.
	    at <Jasmine>
	    at http://localhost:9876/_karma_webpack_/src/lib/radio/radio-button/radio-button-reactive-form.component.spec.ts:73:73
	    at step (http://localhost:9876/home/travis/build/SAP/fundamental-ngx/node_modules/tslib/tslib.es6.js:100:1)
	    at Object.next (http://localhost:9876/home/travis/build/SAP/fundamental-ngx/node_modules/tslib/tslib.es6.js:81:45)
e Headless 62.0.3202.94 (Linux x86_64): Executed 16 of 291 (1 FAILED) (0 secs / 4.349 secs)
```
