### ISSUE TITLE
Bug: Combobox -Using mouse not able to select the option from the combobox list in IE browsers

### ISSUE THREAD

**Issue by puru-hk** [SAP/fundamental-ngx#3298]
Description: Not able to select the option from the combobox list in IE browser windows machine. 

Expected: Should able to select the option from the combobox list 

Getting below error 
HTML1300: Navigation occurred.
fundamental-ngx.netlify.app
ERROR TypeError: Object doesn't support property or method 'composedPath'
   "ERROR"
   {
      [functions]: ,
      __proto__: {
         [functions]: ,
         __proto__: { },
         message: "",
         name: "TypeError",
         Symbol()_8.jqmsgybboch: undefined,
         Symbol()_i.jqmsgybboch: undefined,
         Symbol()_j.jqmsgybboch: undefined,
         Symbol()_k.jqmsgybboch: undefined,
         Symbol()_l.jqmsgybboch: undefined,
         Symbol(INITIAL_VALUE)_n.jqmsgybboch: undefined,
         Symbol(rxSubscriber)_m.jqmsgybboch: undefined
      },
      description: "Object doesn't support property or method 'composedPath'",
      message: "Object doesn't support property or method 'composedPath'",
      name: "TypeError",
      number: -2146827850,
      stack: "TypeError: Object doesn't support property or method 'composedPath'
   at PopoverDirective.prototype._triggerContainsTarget (https://fundamental-ngx.netlify.app/2.js:27056:9)
   at PopoverDirective.prototype._shouldClose (https://fundamental-ngx.netlify.app/2.js:27042:9)
   at Anonymous function (https://fundamental-ngx.netlify.app/2.js:27032:17)
   at Anonymous function (https://fundamental-ngx.netlify.app/main.js:60301:5)
   at ZoneDelegate.prototype.invokeTask (https://fundamental-ngx.netlify.app/polyfills-es5.js:23541:9)
   at onInvokeTask (https://fundamental-ngx.netlify.app/main.js:52365:9)
   at ZoneDelegate.prototype.invokeTask (https://fundamental-ngx.netlify.app/polyfills-es5.js:23541:9)
   at Zone.prototype.runTask (https://fundamental-ngx.netlify.app/polyfills-es5.js:23291:13)
   at ZoneTask.invokeTask (https://fundamental-ngx.netlify.app/polyfills-es5.js:23636:11)
   at invokeTask (https://fundamental-ngx.netlify.app/polyfills-es5.js:25167:7)",
      Symbol()_8.jqmsgybboch: undefined,
      Symbol()_i.jqmsgybboch: undefined,
      Symbol()_j.jqmsgybboch: undefined,
      Symbol()_k.jqmsgybboch: undefined,
      Symbol()_l.jqmsgybboch: undefined,
      Symbol(INITIAL_VALUE)_n.jqmsgybboch: undefined,
      Symbol(rxSubscriber)_m.jqmsgybboch: undefined
   }

ERROR TypeError: Object doesn't support property or method 'composedPath'
   "ERROR"
   {
      [functions]: ,
      __proto__: { },
      description: "Object doesn't support property or method 'composedPath'",
      message: "Object doesn't support property or method 'composedPath'",
      name: "TypeError",
      number: -2146827850,
      stack: "TypeError: Object doesn't support property or method 'composedPath'
   at PopoverDirective.prototype._triggerContainsTarget (https://fundamental-ngx.netlify.app/2.js:27056:9)
   at PopoverDirective.prototype._shouldClose (https://fundamental-ngx.netlify.app/2.js:27042:9)
   at Anonymous function (https://fundamental-ngx.netlify.app/2.js:27032:17)
   at Anonymous function (https://fundamental-ngx.netlify.app/main.js:60301:5)
   at ZoneDelegate.prototype.invokeTask (https://fundamental-ngx.netlify.app/polyfills-es5.js:23541:9)
   at onInvokeTask (https://fundamental-ngx.netlify.app/main.js:52365:9)
   at ZoneDelegate.prototype.invokeTask (https://fundamental-ngx.netlify.app/polyfills-es5.js:23541:9)
   at Zone.prototype.runTask (https://fundamental-ngx.netlify.app/polyfills-es5.js:23291:13)
   at ZoneTask.invokeTask (https://fundamental-ngx.netlify.app/polyfills-es5.js:23636:11)
   at invokeTask (https://fundamental-ngx.netlify.app/polyfills-es5.js:25167:7)",
      Symbol()_8.jqmsgybboch: undefined,
      Symbol()_i.jqmsgybboch: undefined,
      Symbol()_j.jqmsgybboch: undefined,
      Symbol()_k.jqmsgybboch: undefined,
      Symbol()_l.jqmsgybboch: undefined,
      Symbol(INITIAL_VALUE)_n.jqmsgybboch: undefined,
      Symbol(rxSubscriber)_m.jqmsgybboch: undefined
   }

IE version 11.1016

Attached the screenshot 
![image](https://user-images.githubusercontent.com/32538291/93199086-88fc0300-f76b-11ea-8974-78914fb7e54b.png)

**Comment by mykolavorobiov** [comment]
@puru-hk Please check it one more time. If it's reproduce again, please share steps and re-open.
Can't reproduce, verstion **0.25.0-rc.64**
![combobox-ie-select-option](https://user-images.githubusercontent.com/38053194/102343056-c0649080-3fa2-11eb-8f42-91bea3d81ad4.gif)
