### ISSUE TITLE
Platform: Missing exports

### ISSUE THREAD

**Issue by fkolar** [SAP/fundamental-ngx#4087]
#### Is this a bug, enhancement, or feature request?
bug

#### Briefly describe your proposal.
Unable to npm install and build external project that is using latest versions of platfomr 

```
"@fundamental-ngx/core": "0.25.0-rc.51",
"@fundamental-ngx/platform": "0.25.0-rc.51",
```

#### Is there anything else we should know?

```
i304804@C02Y20ECJGH8 rules.git % npm i
npm WARN deprecated popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
> ngx-metaui@9.0.3 postinstall /Users/i304804/Documents/projects/ngx-meta/rules.git
> ngcc --properties es2015 browser module main --first-only --create-ivy-entry-points && node ./decorate-angular-cli.js
Compiling @fundamental-ngx/core : es2015 as esm2015
Compiling @fundamental-ngx/platform : es2015 as esm2015
Error: Error on worker #1: Error: Failed to find exported name of node (class NewFolderComponent {
    constructor(dialogRef) {
        this.dialogRef = dialogRef;
        /**
         * @hidden
         * The current folder in what need to create a new one
         */
        this.currentFolder = this.dialogRef.data.currentFolder;
        /** @hidden */
        this._newFolderName = 'New Folder';
    }
    ngAfterViewInit() {
        const el = this.formControl.elementRef().nativeElement;
        if (el) {
            el.focus();
            this._setSelectionRange(el, 0, this._newFolderName.length);
        }
    }
    /** @hidden */
    _setSelectionRange(el, selectionStart, selectionEnd) {
        const direction = el.selectionDirection;
        el.setSelectionRange(selectionStart, selectionEnd, direction);
    }
}) in '/Users/i304804/Documents/projects/ngx-meta/rules.git/node_modules/@fundamental-ngx/platform/fesm2015/fundamental-ngx-platform.js'.
    at Object.findExportedNameOfNode (/Users/i304804/Documents/projects/ngx-meta/rules.git/node_modules/@angular/compiler-cli/src/ngtsc/imports/src/find_export.js:36:19)
    at LogicalProjectStrategy.emit (/Users/i304804/Documents/projects/ngx-meta/rules.git/node_modules/@angular/compiler-cli/src/ngtsc/imports/src/emitter.js:233:38)
    at ReferenceEmitter.emit (/Users/i304804/Documents/projects/ngx-meta/rules.git/node_modules/@angular/compiler-cli/src/ngtsc/imports/src/emitter.js:72:44)
    at Object.toR3Reference (/Users/i304804/Documents/projects/ngx-meta/rules.git/node_modules/@angular/compiler-cli/src/ngtsc/annotations/src/util.js:249:31)
    at NgModuleDecoratorHandler._toR3Reference (/Users/i304804/Documents/projects/ngx-meta/rules.git/node_modules/@angular/compiler-cli/src/ngtsc/annotations/src/ng_module.js:418:31)
    at /Users/i304804/Documents/projects/ngx-meta/rules.git/node_modules/@angular/compiler-cli/src/ngtsc/annotations/src/ng_module.js:194:83
    at Array.map (<anonymous>)
```

Found so far 3 exports missing to pass the build

**Comment by droshev** [comment]
Can someone check whether this is valid and if not - close the issue
