### ISSUE TITLE
bug(platform): unit tests are failing when host app using Jest

### ISSUE THREAD

**Issue by platon-rov** [SAP/fundamental-ngx#6481]
#### Is this a bug, enhancement, or feature request?

Bug.

#### Briefly describe your proposal.

When the host app which uses our library running tests using Jest (not Jasmine + Karma) unit tests are failing.

Before platform has been split into sub-packages:

```
Test suite failed to run
    TypeError: Cannot read property 'prototype' of undefined
      at Object.ɵɵdefinePipe (../packages/core/src/render3/definition.ts:720:29)
      at node_modules/@fundamental-ngx/platform/bundles/fundamental-ngx-platform.umd.js:25706:44
      at libs/platform/src/lib/components/form/combobox/pipes/highlight.pipe.ts:45:30
      at node_modules/@fundamental-ngx/platform/bundles/fundamental-ngx-platform.umd.js:2:68
      at Object.<anonymous> (node_modules/@fundamental-ngx/platform/bundles/fundamental-ngx-platform.umd.js:5:2)
      at Object.<anonymous> (src/app/app.component.spec.ts:2:1)
```

After platform has been split into sub-packages:

```
Error: Error on worker #2: RangeError: Maximum call stack size exceeded
    at resolveNameHelper (/Users/madrov/coding/my-app/node_modules/typescript/lib/typescript.js:46388:35)
    at resolveName (/Users/madrov/coding/my-app/node_modules/typescript/lib/typescript.js:46386:20)
    at resolveEntityName (/Users/madrov/coding/my-app/node_modules/typescript/lib/typescript.js:47678:42)
    at getSymbolOfNameOrPropertyAccessExpression (/Users/madrov/coding/my-app/node_modules/typescript/lib/typescript.js:80743:28)
    at getSymbolAtLocation (/Users/madrov/coding/my-app/node_modules/typescript/lib/typescript.js:80832:28)
    at Object.getSymbolAtLocation (/Users/madrov/coding/my-app/node_modules/typescript/lib/typescript.js:45218:31)
    at UmdReflectionHost.TypeScriptReflectionHost.getDeclarationOfIdentifier (/Users/madrov/coding/my-app/node_modules/@angular/compiler-cli/src/ngtsc/reflection/src/typescript.js:152:39)
    at UmdReflectionHost.Esm2015ReflectionHost.getDeclarationOfIdentifier (/Users/madrov/coding/my-app/node_modules/@angular/compiler-cli/ngcc/src/host/esm2015_host.js:268:80)
    ...
````

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)

0.32.0 (before splitting)
0.32.1-rc.0 (after splitting)

#### If this is a bug, please provide steps for reproducing it.

Create angular application and configure Jest. 
Create a component with platform's component https://fundamental-ngx.netlify.app/#/platform/table
Run "default" unit tests (e.g. "should create" created by CLI).

**Comment by platon-rov** [comment]
Seems to be not fixed yet. More details provided in first message.
