### ISSUE TITLE
bug(platform): flacky unit tests

### ISSUE THREAD

**Issue by N1XUS** [SAP/fundamental-ngx#7534]
#### Is this a bug, enhancement, or feature request?
bug
#### Briefly describe your proposal.
It was noticed that sometimes during PR checks, the platform's unit tests are failing in a couple of tests. Usually they fail in the icon tab bar, platform table, and wizard generator. 
#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
current

**Comment by dmitry-stepanenko** [comment]
Flaky tests that should be fixed

1. platform-table, `should stop fetching on scroll if currentPage is the last one`
```
Chrome Headless 97.0.4692.71 (Mac OS 10.15.6) TableComponent Page Scrolling should stop fetching on scroll if currentPage is the last one FAILED
        Error: Timeout - Async function did not complete within 5000ms (set by jasmine.DEFAULT_TIMEOUT_INTERVAL)
            at <Jasmine>
Chrome Headless 97.0.4692.71 (Mac OS 10.15.6) ERROR
  An error was thrown in afterAll
  Error: Expected 50 to be 200.
      at <Jasmine>
      at http://localhost:9876/_karma_webpack_/webpack:/libs/platform/src/lib/table/table.component.spec.ts:990:42
      at Generator.next (<anonymous>)
      at fulfilled (http://localhost:9876/_karma_webpack_/webpack:/node_modules/tslib/tslib.es6.js:73:43)
```
2.  platform-search-field, `should return focus to the input field after suggestion item is selected`
```
Error: Expected <button fd-button fd-initial-focus fd-dialog-decisive-button fdtype="transparent" label="Cancel" ng-reflect-fd-type="transparent" ng-reflect-label="Cancel" ng-reflect-compact="true" class="fd-button fd-button--transparent fd-button--compact fd-dialog__decisive-button" type="button">...</button> to be <input type="search" aria-haspopup="true" class="fdp-search-field__input fd-input fd-input-group__input ng-valid ng-dirty ng-touched" id="fdp-search-field-input-48" aria-controls="fdp-search-field-menu-50" aria-expanded="false" placeholder="Search" ng-reflect-model="Apple">. Tip: To check for deep equality, use .toEqual() instead of .toBe().
            at <Jasmine>
            at UserContext.<anonymous> (libs/platform/src/lib/search-field/search-field.component.spec.ts:707:40)
```

3. platform-menu, `should restore focus to the originating trigger after menu close`
```
 Error: Expected <div tabindex="0" role="menuitem" class="fd-menu__link">...</div> to be <button fd-button fd-initial-focus fd-dialog-decisive-button fdtype="transparent" label="Cancel" ng-reflect-fd-type="transparent" ng-reflect-label="Cancel" ng-reflect-compact="true" class="fd-button fd-button--transparent fd-button--compact fd-dialog__decisive-button" type="button">...</button>. Tip: To check for deep equality, use .toEqual() instead of .toBe().
            at <Jasmine>
            at UserContext.<anonymous> (libs/platform/src/lib/menu/menu.spec.ts:285:26)
```
4. platform-menu, `should allow keyboard navigation of items after opening of menu`
```
Error: Expected <div tabindex="0" role="menuitem" class="fd-menu__link">...</div> to be <button fd-button fd-initial-focus fd-dialog-decisive-button fdtype="transparent" label="Cancel" ng-reflect-fd-type="transparent" ng-reflect-label="Cancel" ng-reflect-compact="true" class="fd-button fd-button--transparent fd-button--compact fd-dialog__decisive-button" type="button">...</button>. Tip: To check for deep equality, use .toEqual() instead of .toBe().
            at <Jasmine>
            at UserContext.<anonymous> (libs/platform/src/lib/menu/menu.spec.ts:241:26)
```

**Comment by N1XUS** [comment]
* platform-table: `should get new 50 items per each request`
```
Chrome Headless 97.0.4692.99 (Linux x86_64) TableComponent Page Scrolling should get new 50 items per each request FAILED
	Error: Expected 100 to be 150.
	    at <Jasmine>
	    at libs/platform/src/lib/table/table.component.spec.ts:976:42
	    at Generator.next (<anonymous>)
	    at fulfilled (node_modules/tslib/tslib.es6.js:73:43)
```

**Comment by platon-rov** [comment]
* platform-menu `should hide all menus when when the user TABs off of menu`

```
        Uncaught TypeError: Cannot read properties of undefined (reading 'shadowRoot') thrown
```
