### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'dialogPanelClass')

### ISSUE THREAD

**Issue by ninasim** [SAP/fundamental-ngx#8829]
[[#### Is this a bug, enhancement, or feature request?
bug
#### If this is a bug, please provide steps for reproducing it.
we have created a message box with TemplateRef and using the messageservice to show it. We got the following error in console:
preview-d0bbfde89eb2a.js:2 
        
       ERROR TypeError: Cannot read properties of undefined (reading 'dialogPanelClass')
    at MessageBoxComponent_Template (ɵcmp.js? [sm]:7:5)
    at executeTemplate (shared.ts:544:5)
    at refreshView (shared.ts:391:51)
    at detectChangesInternal (shared.ts:1901:1)
    at ViewRef$1.detectChanges (component_ref.ts:60:5)
    at Object.eval [as next] (dialog-base.class.ts:85:20)
    at ConsumerObserver.next (Subscriber.ts:161:25)
    at Subscriber._next (Subscriber.ts:119:22)
    at Subscriber.next (Subscriber.ts:75:12)
    at BehaviorSubject._subscribe (BehaviorSubject.ts:23:40)
#### Please provide relevant source code if applicable.
https://stackblitz.com/edit/angular-vsa4m4-y7mf3l?file=src%2Fapp%2Ftemplate-based-message-box-example.component.ts
#### Is there anything else we should know?
We tried to overcome the same with empty property value, but this does not solve the error. Any proposals are welcome

**Comment by platon-rov** [comment]
You have wrong parameters passed to the `open` method, it accepts two - first is the template and second is the config object and you passed two objects. Please see docs https://fundamental-ngx.netlify.app/#/core/message-box#template-based.

**Comment by ninasim** [comment]
Hi, 

I am using the ._messageBoxService.open with content: templateRef,  so this is not supported or?.

as it is possible to put as a content a templateRef of a message.


const messageBoxRef = this._messageBoxService.open(
          {
            title,
            **content: message,**
            approveButton: 'Ok',
            approveButtonCallback: () => {
              if (closeCallback !== undefined) {
                closeCallback();
              }
              messageBoxRef.close('Approved');
            },
            closeButtonCallback: () => {
              if (closeCallback !== undefined) {
                closeCallback();
              }
              messageBoxRef.dismiss('Dismissed');
            },
          },
          {
            type,
            showSemanticIcon: true
          }
        );

**Comment by ninasim** [comment]
it's not possible to specify body in the template and header in the config, we have to chose one way, we should implement according to this example:

We should implement message box the https://fundamental-ngx.netlify.app/#/core/message-box#template-based
