### ISSUE TITLE
NG0203 on version 0.37

### ISSUE THREAD

**Issue by slithzerikai** [SAP/fundamental-ngx#9031]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal

Getting an NG0203 error on various modules both platform and core. 

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)

Using angular 14.2 and Fundamental 0.37.0-rc.23

#### Is there anything else we should know?

main.ts:51 Error: NG0203: inject() must be called from an injection context such as a constructor, a factory function, a field initializer, or a function used with `EnvironmentInjector#runInContext`. Find more at https://angular.io/errors/NG0203
    at injectInjectorOnly (core.mjs:4768:15)
    at Module.ɵɵinject (core.mjs:4779:12)
    at Object.FundamentalNgxPlatformModule_Factory [as useFactory] (fundamental-ngx-platform.mjs:70:1)
    at Object.factory (core.mjs:8806:38)
    at R3Injector.hydrate (core.mjs:8719:35)
    at R3Injector.get (core.mjs:8607:33)
    at injectInjectorOnly (core.mjs:4782:33)
    at ɵɵinject (core.mjs:4786:12)
    at useValue (core.mjs:8399:65)
    at R3Injector.resolveInjectorInitializers (core.mjs:8656:17)

Haven't been able to create a stackblitz to reproduce the issue.

**Comment by g-cheishvili** [comment]
@slithzerikai Can you provide reproduction steps?

**Comment by slithzerikai** [comment]
> @slithzerikai Can you provide reproduction steps?

I'm afraid all I can do is post my package dependencies and point out that although the application seems to compile, the error shows in the browser console.

It all worked fine until I upgraded to Angular 14 and the latest fundamental library version.

It is caught in the main.ts file:

```
platformBrowserDynamic()
  .bootstrapModule(AppModule)
  .catch((err) => console.error(err));
```


```
  "dependencies": {
    "@angular/animations": "^14.0.0",
    "@angular/cdk": "^14.0.0",
    "@angular/common": "^14.0.0",
    "@angular/compiler": "^14.0.0",
    "@angular/core": "^14.0.0",
    "@angular/forms": "^14.0.0",
    "@angular/material": "^14.0.0",
    "@angular/platform-browser": "^14.0.0",
    "@angular/platform-browser-dynamic": "^14.0.0",
    "@angular/router": "^14.0.0",
    "@angular/flex-layout": "^14.0.0-beta.41",
    "rxjs": "^7.4.0",
    "@fundamental-ngx/core": "^0.37.0-rc.23",
    "@fundamental-ngx/moment-adapter": "^0.37.0-rc.23",
    "@fundamental-ngx/platform": "^0.37.0-rc.23",
    "@sap-theming/theming-base-content": "^11.1.44",
    "fundamental-styles": "~0.26.0-rc.27",
    "@msgpack/msgpack": "^2.7.2",
    "@ng-bootstrap/ng-bootstrap": "^13.1.1",
    "@ngneat/transloco": "^4.0.0",
    "angular2-hotkeys": "^13.1.0",
    "arrow-line": "^0.7.5",
    "bootstrap": "^4.6.1",
    "canvas-arrow": "^1.1.1",
    "compression": "^1.7.4",
    "core-js": "^3.7.0",
    "date-fns": "^2.17.0",
    "delay": "^5.0.0",
    "flag-icons": "^6.4.4",
    "jspdf": "^2.5.1",
    "lodash-es": "^4.17.21",
    "moment": "^2.29.1",
    "ngx-moment": "^6.0.2",
    "ngx-print": "^1.2.1",
    "ngx-ui-tour-ng-bootstrap": "^11.3.2",
    "popper.js": "^1.16.1",
    "squirrelly": "^8.0.8",
    "tslib": "^2.3.0",
    "typescript-memoize": "^1.1.0",
    "uuid": "^8.3.2",
    "world-map-country-shapes": "^1.0.0",
    "xng-breadcrumb": "^7.2.0",
    "zone.js": "^0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^14.2.10",
    "@angular-eslint/builder": "^14.4.0",
    "@angular-eslint/eslint-plugin": "^14.4.0",
    "@angular-eslint/eslint-plugin-template": "^14.4.0",
    "@angular-eslint/schematics": "^14.4.0",
    "@angular-eslint/template-parser": "^14.4.0",
    "@angular/cli": "^14.2.10",
    "@angular/compiler-cli": "^14.0.0",
    "@angular/language-service": "^14.0.0",
    "@ngneat/until-destroy": "^9.0.0",
    "@ngx-rocket/scripts": "^5.2.1",
    "@types/jasmine": "^3.6.2",
    "@types/jasminewd2": "^2.0.8",
    "@types/lodash-es": "^4.17.6",
    "@types/node": "^12.20.37",
    "@types/uuid": "^8.3.0",
    "@typescript-eslint/eslint-plugin": "^5.36.2",
    "@typescript-eslint/parser": "^5.36.2",
    "dateformat": "^5.0.2",
    "eslint": "^8.23.0",
    "eslint-plugin-import": "latest",
    "eslint-plugin-jsdoc": "latest",
    "eslint-plugin-prefer-arrow": "latest",
    "eslint-plugin-react": "^7.28.0",
    "git-describe": "^4.1.0",
    "htmlhint": "^1.1.2",
    "https-proxy-agent": "^5.0.0",
    "husky": "^7.0.0",
    "ngc": "^1.0.0",
    "postcss": "^8.4.5",
    "prettier": "^2.2.1",
    "pretty-quick": "^3.1.3",
    "replace-in-file": "^6.3.2",
    "stylelint": "^14.5.0",
    "stylelint-config-prettier": "^9.0.3",
    "stylelint-config-recommended-scss": "^5.0.2",
    "stylelint-config-standard": "^25.0.0",
    "ts-node": "^10.1.0",
    "typescript": "^4.6.2"
  }
```

**Comment by g-cheishvili** [comment]
@slithzerikai check this out. You posted package.json with not fixed versions. I used latest ng14 compatible versions and created basic app with dependencies you have on your package.json
https://stackblitz.com/edit/angular-ivy-ouktb7?file=src/index.html

**Comment by slithzerikai** [comment]
With those versions it doesn't even compile for me:

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: vca-ui@0.10.0
npm ERR! Found: @sap-theming/theming-base-content@11.1.44
npm ERR! node_modules/@sap-theming/theming-base-content
npm ERR!   @sap-theming/theming-base-content@"11.1.44" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @sap-theming/theming-base-content@"11.1.47" from @fundamental-ngx/core@0.37.1
npm ERR! node_modules/@fundamental-ngx/core
npm ERR!   @fundamental-ngx/core@"0.37.1" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

**Comment by g-cheishvili** [comment]
If you will face the issue again, please report back with a minimal reproduction with stackblitz example. Otherwise I can not reproduce it
